In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
def simple_interest(p,r,t):
  print('The principal is:',p)
  print('The timeperiod is:',t)
  print('The rate of interest:',r)
  si=(p*t*r)/100
  print('The simple interest:',si)
  return si
simple_interest(8,6,8)

The principal is: 8
The timeperiod is: 8
The rate of interest: 6
The simple interest: 3.84


3.84

In [ ]:
#1
set1=["aman", "222", 777, 400.4]
t=tuple(set1)
print(t)
print(type(t))

('aman', '222', 777, 400.4)
<class 'tuple'>


In [ ]:
#2
dict1={'Rollno':'CB.EN.U4CSE20217','FirstName':'Dheepthi','LastName':'Priyangha','DateOfBirth':'5-11-2002'}
for i in dict1:
  print(i,'-',dict1[i])

Rollno - CB.EN.U4CSE20217
FirstName - Dheepthi
LastName - Priyangha
DateOfBirth - 5-11-2002


In [ ]:
#3
import numpy as np
from numpy import random
arr=random.rand(3,5)
print(arr)

[[0.6133479  0.48985646 0.05655685 0.62929134 0.43080816]
 [0.92312726 0.58331939 0.22680224 0.71466083 0.08923426]
 [0.12749557 0.35660026 0.46644534 0.23716283 0.65695394]]


In [ ]:
#4
import numpy as np
from numpy import random
n=random.random()
print(n)
a=np.abs(-1234)
print(a)



0.6906243188822148
1234


In [ ]:
#5
r=random.randint(20,90)
print(r)


76


In [ ]:
#6
l=[11,12,13,14,15]
a=random.choice(l)
print(a)
random.shuffle(l)
print(l)


11
[13, 15, 14, 11, 12]


In [ ]:
#7
f = open("n.txt", 'w')
f.write("The King is Dead, Long Live The King")
f.close()
f = open("n.txt", "r")
print(f.read())

The King is Dead, Long Live The King


In [ ]:
#8
n=int(input())
if(n>0):
  print("The number is postive")
elif(n<0):
  print("The number is negative")
else:
  print("NULL")
for i in range(20):
  if(i%2==0):
    continue
  print(i)
for var in "DheepthiPriyangha":
    if var == "P":
        break
    print(var)

-9
The number is negative
1
3
5
7
9
11
13
15
17
19
D
h
e
e
p
t
h
i


In [ ]:
#9
str="The King is Dead, Long Live The King"
print(str)
print(str[0])
print(str[3:6])
print(str[3:])
print(str.split())




The King is Dead, Long Live The King
T
 Ki
 King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


In [ ]:
#10
arr=[1.0,4.0,5.0,8.0]
print(arr[:2])


[1.0, 4.0]


In [ ]:
#11
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#12
arr=np.array([[1,2,3],[4,5,6]])
print(arr[1])
#print(arr([]))
print(len(arr))

[4 5 6]
2


In [ ]:
#13
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
a=arr1.reshape(5,2)
print(a)
print(arr1.transpose())

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#14




In [ ]:
#15
arr=[1,2,3]
for i in range(len(arr)):
  arr[i]=9
print(arr)

[9, 9, 9]


In [ ]:
#16
arr=np.array([2,4,5])
sum=0
for i in arr:
  sum+=i
print("The sum of elements in the array is :",sum)


The sum of elements in the array is : 11


In [ ]:
#17
arr=[77,74,75]
p=1
for i in range(len(arr)):
  p=p*arr[i]
print('The product of the elements in the array is :',p)

The product of the elements in the array is : 427350


In [ ]:
#18
a1=[2,1,9,1,2,22,1,1,4,55,6,2,56]
for i in a1:
  sum=+i
print('mean=',sum/len(a1))
print('Max=',max(a1))
print('Min=',min(a1))




mean= 4.3076923076923075
Max= 56
Min= 1


In [ ]:
#19
arr=[1, 1, 4, 5, 5, 5, 7, 3, 2] 
l=[]
for i in arr:
  if(arr.count(i)==1):
    l.append(i)
l.sort()
print(l)
  


[2, 3, 4, 7]


In [ ]:
#20
a=[1,2,3]
b=[0,1,1]
l=[]
for i in range(len(a)):
  l.append(a[i]*b[i])
print(l)
  

[0, 2, 3]


In [ ]:
#21
import numpy as np
from numpy.linalg import eig
a = np.array([[2, -12], 
              [1, -5]])
w,v=eig(a)
print('E-value:', w)
print('E-vector', v)

E-value: [-1. -2.]
E-vector [[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]


In [ ]:
#22
a=np.array([[11, 22, 11, 31], [25, 33, 31, 28]])



In [ ]:
def myfunc():
  return None
print("Using __doc__:") 
print(myfunc.__doc__)
print("Using help:") 
help(myfunc)

Using __doc__:
None
Using help:
Help on function myfunc in module __main__:

myfunc()



In [ ]:
import pandas as pd
df = pd.read_csv("/content/world_population.csv")
df

Rank CCA3            Country           Capital Continent  \
0      36  AFG        Afghanistan             Kabul      Asia   
1     138  ALB            Albania            Tirana    Europe   
2      34  DZA            Algeria           Algiers    Africa   
3     213  ASM     American Samoa         Pago Pago   Oceania   
4     203  AND            Andorra  Andorra la Vella    Europe   
..    ...  ...                ...               ...       ...   
229   226  WLF  Wallis and Futuna          Mata-Utu   Oceania   
230   172  ESH     Western Sahara          El Aaiún    Africa   
231    46  YEM              Yemen             Sanaa      Asia   
232    63  ZMB             Zambia            Lusaka    Africa   
233    74  ZWE           Zimbabwe            Harare    Africa   

     2022 Population  2020 Population  2015 Population  2010 Population  \
0           41128771         38972230         33753499         28189672   
1            2842321          2866849          2882481          2913399   
2           44903225         43451666         39543154         35856344   
3              44273            46189            51368            54849   
4              79824            77700            71746            71519   
..               ...              ...              ...              ...   
229            11572            11655            12182            13142   
230           575986           556048           491824           413296   
231         33696614         32284046         28516545         24743946   
232         20017675         18927715         16248230         13792086   
233         16320537         15669666         14154937         12839771   

     2000 Population  1990 Population  1980 Population  1970 Population  \
0           19542982         10694796         12486631         10752971   
1            3182021          3295066          2941651          2324731   
2           30774621         25518074         18739378         13795915   
3              58230            47818            32886            27075   
4              66097            53569            35611            19860   
..               ...              ...              ...              ...   
229            14723            13454            11315             9377   
230           270375           178529           116775            76371   
231         18628700         13375121          9204938          6843607   
232          9891136          7686401          5720438          4281671   
233         11834676         10113893          7049926          5202918   

     Area (km²)  Density (per km²)  Growth Rate  World Population Percentage  
0        652230            63.0587       1.0257                         0.52  
1         28748            98.8702       0.9957                         0.04  
2       2381741            18.8531       1.0164                         0.56  
3           199           222.4774       0.9831                         0.00  
4           468           170.5641       1.0100                         0.00  
..          ...                ...          ...                          ...  
229         142            81.4930       0.9953                         0.00  
230      266000             2.1654       1.0184                         0.01  
231      527968            63.8232       1.0217                         0.42  
232      752612            26.5976       1.0280                         0.25  
233      390757            41.7665       1.0204                         0.20  

[234 rows x 17 columns]

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
import pandas as pd
pd.read_csv('/content/world_population.csv')


Rank CCA3            Country           Capital Continent  \
0      36  AFG        Afghanistan             Kabul      Asia   
1     138  ALB            Albania            Tirana    Europe   
2      34  DZA            Algeria           Algiers    Africa   
3     213  ASM     American Samoa         Pago Pago   Oceania   
4     203  AND            Andorra  Andorra la Vella    Europe   
..    ...  ...                ...               ...       ...   
229   226  WLF  Wallis and Futuna          Mata-Utu   Oceania   
230   172  ESH     Western Sahara          El Aaiún    Africa   
231    46  YEM              Yemen             Sanaa      Asia   
232    63  ZMB             Zambia            Lusaka    Africa   
233    74  ZWE           Zimbabwe            Harare    Africa   

     2022 Population  2020 Population  2015 Population  2010 Population  \
0           41128771         38972230         33753499         28189672   
1            2842321          2866849          2882481          2913399   
2           44903225         43451666         39543154         35856344   
3              44273            46189            51368            54849   
4              79824            77700            71746            71519   
..               ...              ...              ...              ...   
229            11572            11655            12182            13142   
230           575986           556048           491824           413296   
231         33696614         32284046         28516545         24743946   
232         20017675         18927715         16248230         13792086   
233         16320537         15669666         14154937         12839771   

     2000 Population  1990 Population  1980 Population  1970 Population  \
0           19542982         10694796         12486631         10752971   
1            3182021          3295066          2941651          2324731   
2           30774621         25518074         18739378         13795915   
3              58230            47818            32886            27075   
4              66097            53569            35611            19860   
..               ...              ...              ...              ...   
229            14723            13454            11315             9377   
230           270375           178529           116775            76371   
231         18628700         13375121          9204938          6843607   
232          9891136          7686401          5720438          4281671   
233         11834676         10113893          7049926          5202918   

     Area (km²)  Density (per km²)  Growth Rate  World Population Percentage  
0        652230            63.0587       1.0257                         0.52  
1         28748            98.8702       0.9957                         0.04  
2       2381741            18.8531       1.0164                         0.56  
3           199           222.4774       0.9831                         0.00  
4           468           170.5641       1.0100                         0.00  
..          ...                ...          ...                          ...  
229         142            81.4930       0.9953                         0.00  
230      266000             2.1654       1.0184                         0.01  
231      527968            63.8232       1.0217                         0.42  
232      752612            26.5976       1.0280                         0.25  
233      390757            41.7665       1.0204                         0.20  

[234 rows x 17 columns]

In [ ]:
import pandas as pd
df=pd.read_csv('https://raw.githubusercontent.com/flaviovdf/evcomp2018/master/data/nba_salaries.csv')
print(df.to_string())

                       PLAYER POSITION                    TEAM     SALARY
0                Paul Millsap       PF           Atlanta Hawks  18.671659
1                  Al Horford        C           Atlanta Hawks  12.000000
2              Tiago Splitter        C           Atlanta Hawks   9.756250
3                 Jeff Teague       PG           Atlanta Hawks   8.000000
4                 Kyle Korver       SG           Atlanta Hawks   5.746479
5             Thabo Sefolosha       SF           Atlanta Hawks   4.000000
6                  Mike Scott       PF           Atlanta Hawks   3.333333
7               Kent Bazemore       SF           Atlanta Hawks   2.000000
8             Dennis Schroder       PG           Atlanta Hawks   1.763400
9            Tim Hardaway Jr.       SG           Atlanta Hawks   1.304520
10             Walter Tavares        C           Atlanta Hawks   1.000000
11           Jason Richardson       SG           Atlanta Hawks   0.947276
12            Lamar Patterson       SG

In [ ]:
df1=pd.read_csv('/content/world_population.csv')

